/*
This file is generated by Jopi.js. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import C from "../../mod_adminLayout/@alias/uiComponents/page.layout.admin/index.tsx";
export default C;