/*
This file is generated by JopiRewrite. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import C from "../../mod_sample/@alias/uiBlocks/page.layout.admin/index.tsx";
export default C;