/*
This file is generated by JopiRewrite. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import {routeBindPage, routeBindVerb} from "jopi-rewrite/generated";
import c_r1 from "../mod_sample/@routes/page.tsx";
import c_r2 from "../mod_sample/@routes/login/page.tsx";
import f_r3 from "../mod_sample/@routes/login/onPOST.ts";
import {RouteConfig} from "jopi-rewrite";
import routeConfig1 from "../mod_sample/@routes/login/config.ts";

export default async function(webSite) {
    await routeBindPage(webSite, c_r1, {"route":"/","attributs":{},"filePath":"src/mod_sample/@routes/page.tsx"});
    await routeBindPage(webSite, c_r2, {"route":"/login","attributs":{"configFile":"/Users/johan/Temps/src/mod_sample/@routes/login/config.ts"},"filePath":"src/mod_sample/@routes/login/page.tsx"});
    await routeBindVerb(webSite, f_r3, {"verb":"POST","route":"/login","attributs":{"configFile":"/Users/johan/Temps/src/mod_sample/@routes/login/config.ts"},"filePath":"/Users/johan/Temps/src/mod_sample/@routes/login/onPOST.ts"});
    await routeConfig1(new RouteConfig(webSite, "/login"));
}