/*
This file is generated by JopiRewrite. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import {routeBindPage, routeBindVerb} from "jopijs/generated";
import c_r1 from "../mod_sample/@routes/forms/page.tsx";
import c_r2 from "../mod_sample/@routes/tests/page.tsx";
import c_r3 from "../mod_sample/@routes/page.tsx";
import c_r4 from "../mod_sample/@routes/login/page.tsx";
import f_r5 from "../mod_sample/@routes/login/onPOST.ts";
import {RouteConfig} from "jopijs";
import routeConfig1 from "../mod_sample/@routes/login/config.ts";

export default async function(webSite) {
    await routeBindPage(webSite, c_r1, {"route":"/forms","attributs":{},"filePath":"src/mod_sample/@routes/forms/page.tsx"});
    await routeBindPage(webSite, c_r2, {"route":"/tests","attributs":{},"filePath":"src/mod_sample/@routes/tests/page.tsx"});
    await routeBindPage(webSite, c_r3, {"route":"/","attributs":{},"filePath":"src/mod_sample/@routes/page.tsx"});
    await routeBindPage(webSite, c_r4, {"route":"/login","attributs":{"configFile":"/Users/johan/Temps/src/mod_sample/@routes/login/config.ts"},"filePath":"src/mod_sample/@routes/login/page.tsx"});
    await routeBindVerb(webSite, f_r5, {"verb":"POST","route":"/login","attributs":{"configFile":"/Users/johan/Temps/src/mod_sample/@routes/login/config.ts"},"filePath":"/Users/johan/Temps/src/mod_sample/@routes/login/onPOST.ts"});
    await routeConfig1(new RouteConfig(webSite, "/login"));
}