/*
This file is generated by JopiRewrite. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/


import modUiInit1 from "../mod_sample/uiInit.tsx";

export default function(registry) {

    modUiInit1(registry);
    registry.events.sendEvent("app.init.ui", {myModule: registry});
}