/*
This file is generated by JopiRewrite. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/


import declareRoutes from "./declareServerRoutes.js";
import modServerInit1 from "../mod_sample/serverInit.ts";

export default async function(registry, onWebSiteCreated) {

    await modServerInit1(registry);
    onWebSiteCreated((webSite) => declareRoutes(webSite));
}