/*
This file is generated by Jopi.js. Do not modify it.
See file ARCHITECTURE.md at the root of the project for instructions.
*/
import {createStaticEvent} from "jopi-toolkit/jk_events";
import I1 from "../../mod_learning/@alias/events/test.hello/l1/index.ts";
import I2 from "../../mod_learning/@alias/events/test.hello/l2/index.ts";

export const list = [I1,I2,];
export const event = createStaticEvent("test.hello", list);
export default event;